---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
{{ if eq .SVC_LATENCY "true" }}
    - name: serviceLatency
      svcTimeout: 10s
{{ end }}
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}

jobs:
  - name: sdn-ovn-networkpolicy-egress-restricted
    namespace: sdn-ovn-restricted
    jobIterations: {{.SDN_OVN_RESTRICTED_ITERATION}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churn: {{.CHURN}}
    churnCycles: {{.CHURN_CYCLES}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    churnDeletionStrategy: {{.CHURN_DELETION_STRATEGY}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:
      - objectTemplate: postgres-deployment.yml
        replicas: {{.POD_RPLICAS}}
        inputVars:
          readinessPeriod: 1
          nodeSelector: "{{.POD_NODE_SELECTOR}}"
          anplabel: "sdn-ovn-restricted"

      - objectTemplate: postgres-service.yml
        replicas: {{.POD_RPLICAS}}
        inputVars:
          anplabel: "sdn-ovn-restricted"

      - objectTemplate: perfapp-deployment.yml
        replicas: {{.POD_RPLICAS}}
        inputVars:
          readinessPeriod: 10
          livenessPeriod: 10
          nodeSelector: "{{.POD_NODE_SELECTOR}}"
          anplabel: "sdn-ovn-restricted"

      - objectTemplate: perfapp-service.yml
        replicas: 1
        inputVars:
          anplabel: "sdn-ovn-restricted"

      - objectTemplate: cross-ns-traffic-app-ata.yml
        replicas: {{.POD_RPLICAS}}
        inputVars:
          readinessPeriod: 10
          livenessPeriod: 10
          nodeSelector: "{{.POD_NODE_SELECTOR}}"
          anplabel: "sdn-ovn-restricted"

      - objectTemplate: egress-traffic-app.yml
        replicas: 2
        inputVars:
          nodeSelector: "{{.POD_NODE_SELECTOR}}"
          anplabel: "sdn-ovn-restricted"

      - objectTemplate: networkpolicy-deny-all.yml
        replicas: 1

      - objectTemplate: networkpolicy-allowdns.yml
        replicas: 1
        
      - objectTemplate: networkpolicy-ingress-within-same-ns.yml
        replicas: {{.NETWORKPOLICY_RPLICAS}}
        inputVars:
          selected_pod_type: "perfdb"
          ingress_pod_type: "perfapp"

      - objectTemplate: networkpolicy-egress-within-same-ns.yml
        replicas: {{.NETWORKPOLICY_RPLICAS}}
        inputVars:
          selected_pod_type: "perfapp"
          egress_pod_type: "perfdb"
          ns_label: "anplabel"
          ns_label_value: "sdn-ovn-restricted"
          pod_label: "type"
          pod_label_value: perfdb         

      - objectTemplate: sdn-default-egress-firewall.yml
        replicas: 1

      - objectTemplate: egress-external-traffic-app.yml
        replicas: 1
        inputVars:
          nodeSelector: "{{.WORKLOAD_POD_NODE_SELECTOR}}"
          anplabel: "sdn-ovn-restricted"