apiVersion: policy.networking.k8s.io/v1alpha1
kind: BaselineAdminNetworkPolicy
metadata:
  name: default
spec:
  subject:
    namespaces: {}
  ingress:
  - name: "deny-all-ingress-to-any-ns"
    action: "Deny"
    from:
    - namespaces:
        namespaceSelector: {}
  egress:
  - name: "deny-all-egress-to-any-ns"
    action: "Deny"
    to:
    - namespaces:
        namespaceSelector: {}