apiVersion: v1
kind: Pod
metadata:
  name: {{.anplabel}}-{{.Iteration}}-ata-{{.Replica}}
  labels:
    type: anp-traffic-app-{{.Iteration}}-{{.Replica}}
    anplabel: {{.anplabel}}
spec:
  nodeSelector: {{.nodeSelector}}
  containers:
  - name: anp-traffic-app
    image: quay.io/openshift-psap-qe/ubi9-minimal
    imagePullPolicy: Always
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - while true;
      do
      curl -Is http://anp-traffic-service.anp-restricted-1.svc.cluster.local:8080 | head -n 1;
      sleep 2;
      curl -Is http://anp-traffic-service.anp-open-1.svc.cluster.local:8080 | head -n 1;
      sleep 2;
      curl -Is http://anp-traffic-service.anp-test-1.svc.cluster.local:8080 | head -n 1;
      sleep 2;      
      curl -Is http://anp-traffic-service.anp-unknown-1.svc.cluster.local:8080 | head -n 1;
      done
    ports:
    - containerPort: 8080
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
