kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.anplabel}}-{{.Iteration}}-app-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        name: perfapp-{{.Iteration}}-{{.Replica}} 
        anplabel: {{.anplabel}}
        type: perfapp-{{.Iteration}}-{{.Replica}}
        trafficapp: perfapp
        podsn: {{.anplabel}}-{{.Iteration}}-{{.Replica}}  
    spec:
      nodeSelector: {{.nodeSelector}}
      containers:
      - name: perfapp
        image: quay.io/cloud-bulldozer/perfapp:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: {{ .readinessPeriod }}
          failureThreshold: 1
          timeoutSeconds: 60
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: {{ .livenessPeriod }}
          failureThreshold: 1
          timeoutSeconds: 15
          initialDelaySeconds: 30
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          value: admin
        - name: POSTGRESQL_PASSWORD
          value: secret
        - name: POSTGRESQL_DATABASE
          value: node-density
        - name: POSTGRESQL_HOSTNAME
          value: postgres-{{.Iteration}}-{{.Replica}}
        - name: POSTGRESQL_PORT
          value: '5432'
        - name: POSTGRESQL_RETRY_INTERVAL
          value: '5'
        securityContext:
          privileged: false
      restartPolicy: Always
  replicas: 3
  selector:
    matchLabels:
      name: perfapp-{{.Iteration}}-{{.Replica}}
  strategy:
    type: RollingUpdate
