---
kind: Service
apiVersion: v1
metadata:
  name: probe-detectd-nginx-service
spec:
  selector:
    app: probe-detectd-nginx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
  sessionAffinity: None

