{
 "title": "PerfScale Performance Analysis Dashboard",
 "description": "Dashboards for obsessive people",
 "tags": [ "RiskyAdventure" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "_master_node",
    "label": "Master",
    "query": {
     "query": "label_values(kube_node_role{role=\"master\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace!=\"(cluster-density.*|node-density-.*)\"}, namespace)"
    }
   },
   { "name": "interval", "label": "interval", "query": "2m,3m,4m,5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(apiserver_current_inflight_requests, job)"
    }
   },
   { "name": "Node", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Total Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cluster_version{type=\"cluster\"}"
      }
     ]
    },
    {
     "title": "Current namespace Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_namespace_status_phase) by (phase)",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Current Node Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(kube_node_info{})", "legendFormat": "Number of nodes" },
      {
       "expr": "sum(kube_node_status_condition{status=\"true\"}) by (condition) > 0",
       "legendFormat": "Ready of nodes"
      }
     ]
    },
    {
     "title": "Current Pod Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{}) by (phase) > 0",
       "legendFormat": "{{ phase}} Pods"
      }
     ]
    },
    {
     "title": "OVN Pod Restarts Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by(container) (kube_pod_container_status_restarts_total{namespace=\"openshift-ovn-kubernetes\"}) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cluster Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster CPU Usage (1m avg)",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{id=\"/\", kubernetes_io_hostname=~\"^$Node$\"}[1m])) * 100) / sum(machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Cluster Filesystem Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/nvme.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/nvme.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/nvme.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/nvme.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "API Server Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Terminations",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_terminations_total{job=\"$job\"}[1m]))"
      }
     ]
    },
    {
     "title": "API Pod Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"apiserver\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Secret Cache Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apiserver_envelope_encryption_dek_cache_fill_percent{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Top Resource Watches",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 13, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, max by (kind)(apiserver_registered_watchers{job=\"$job\"}))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Unavailable Apiservice",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max by (name)(max_over_time(aggregator_unavailable_apiservice{job=\"$job\"}[$__interval])) > 0.1",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "API Server CPU usage in CPU Seconds",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(process_cpu_seconds_total{job=~\"apiserver|kube-controller-manager|scheduler|etcd\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Slowest Requests (P90) - 5min",
     "type": "timeseries",
     "description": " Using recording rules via kube stack prometheus",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(3, cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{job=\"$job\",quantile=\"0.9\", subresource=\"\"})",
       "legendFormat": "{{resource}}.{{group}}: {{verb}} "
      }
     ]
    },
    {
     "title": "rest_client_request_duration_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, service, verb) (rate(rest_client_request_duration_seconds_bucket{job=~\"kube-controller-manager|scheduler|check-endpoints|kubelet\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "apiserver_request_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by(resource, code, verb, system_client) (irate(apiserver_request_total{job=\"apiserver\", system_client!=\"\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "SDN Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "OVN Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "NBDB Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ovn_db_db_size_bytes{db_name=~\"OVN_Northbound\"}",
       "legendFormat": "{{pod}}:{{db_name}}"
      }
     ]
    },
    {
     "title": "SBDB Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ovn_db_db_size_bytes{db_name=~\"OVN_Southbound\"}",
       "legendFormat": "{{pod}}:{{db_name}}"
      }
     ]
    },
    {
     "title": "NBDB Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_rss{pod=~\"ovnkube-master.*|ovnkube-node.*\", container=~\"nbdb\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SBDB Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_rss{pod=~\"ovnkube-master.*|ovnkube-node.*\", container=~\"sbdb\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Northd Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_rss{pod=~\"ovnkube-master.*|ovnkube-node.*\", container=~\"northd\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum by(instance) (node_filefd_allocated)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OVN Node POD Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_rss{pod=~\"ovnkube-node-.*\", container=~\"kube-rbac-proxy-node|kube-rbac-proxy-ovn-metrics|nbdb|northd|ovn-acl-logging|ovn-controller|ovnkube-controller|sbdb\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "OVN Control Plane POD Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_rss{pod=~\"ovnkube-control-plane.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OVN Kube Controller Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_rss{container=~\"ovnkube-controller\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OVN Controller Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_rss{container=~\"ovn-controller\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OVN Node Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, sum by(pod) (irate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"ovnkube-node.*\", namespace=~\"openshift-ovn-kubernetes\"}[$interval]))) * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OVN Master/ControlPlane CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, irate(container_cpu_usage_seconds_total{pod=~\"ovnkube-control-plane-.*\"}[5m])) * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OVN Node Pod Detailed Mem Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{namespace=\"openshift-ovn-kubernetes\", pod=~\"ovnkube-node-.*\", container!~\"POD|\"}",
       "legendFormat": "{{pod}}:{{container}}"
      }
     ]
    },
    {
     "title": "OVN Master/ControlPlane Pod Details",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{namespace=\"openshift-ovn-kubernetes\", pod=~\"ovnkube-control-plane-.*|ovnkube-master.*\", container!~\"POD|\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "ovnControllerFlowGeneration95Perc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "ovn_controller_flow_generation_95th_percentile",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovnControllerFlowInstallation95Perc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "ovn_controller_flow_installation_95th_percentile",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovnControllerRconnDiscarded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(ovn_controller_rconn_discarded)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ovnControllerRconnOverflow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(ovn_controller_rconn_overflow)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OVS Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "ovsVswitchdCPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by(node) (irate(container_cpu_usage_seconds_total{id=~\"/system.slice/ovs-vswitchd.service\"}[5m])*100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ovsdbServerCPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/system.slice/ovsdb-server.service\"}[2m]) * 100) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OVS DB Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ovs_db_process_resident_memory_bytes",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovs_vswitchd_dp_flows_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      { "expr": "ovs_vswitchd_dp_flows_total", "legendFormat": "{{pod}}:{{datapath}}" }
     ]
    },
    {
     "title": "ovsFlowsCounter - br-int",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "ovs_vswitchd_bridge_flows_total{bridge=\"br-int\"}",
       "legendFormat": "{{pod}}:{{bridge}}"
      }
     ]
    },
    {
     "title": "ovsFlowsCounter - br-ex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "ovs_vswitchd_bridge_flows_total{bridge=\"br-ex\"}",
       "legendFormat": "{{pod}}:{{bridge}}"
      }
     ]
    },
    {
     "title": "ovsVswitchdRconnDiscarded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(ovs_vswitchd_rconn_discarded)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovsVswitchdRconnOverflow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 7, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(ovs_vswitchd_rconn_overflow)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovsVswitchdStreamOpen",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ovs_vswitchd_stream_open)", "legendFormat": "{{pod}}" }
     ]
    }
   ]
  },
  {
   "title": "OVN Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "ovnkube_clustermanager_leader",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ovnkube_clustermanager_leader", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "ovnkube_clustermanager_ready_duration_seconds",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "ovnkube_clustermanager_ready_duration_seconds{namespace=\"openshift-ovn-kubernetes\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovnkube_node_ready_duration_seconds",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, max_over_time(ovnkube_node_ready_duration_seconds[12h]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovnkube_controller_sync_duration_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "topk(10, max_over_time(ovnkube_controller_sync_duration_seconds[12h]))",
       "legendFormat": "{{pod}}:{{resource_name}}"
      }
     ]
    },
    {
     "title": "ovnkube_controller_ready_duration_seconds",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, max_over_time(ovnkube_controller_ready_duration_seconds[12h]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ovnkube_controller_pod_creation_latency_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "ovnkube_controller_pod_creation_latency_seconds_count{namespace=\"openshift-ovn-kubernetes\"}",
       "legendFormat": "{{pod}}:{{container}}"
      }
     ]
    },
    {
     "title": "ovnkube_controller_pod_event_latency_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(pod, event, le) (rate(ovnkube_controller_pod_event_latency_seconds_bucket[5m])))",
       "legendFormat": "{{pod}}:{{event}}"
      }
     ]
    },
    {
     "title": "Etcd Request Latency",
     "type": "heatmap",
     "description": "All Calls Heatmap to etcd server. Show etcd high level  if etcd is source of slowness. Adding a recording rule will help.",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by(le) (increase(etcd_request_duration_seconds_bucket{job=\"$job\"}[1m]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "ovnkube_controller_sync_service_latency_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, container, instance) (rate(ovnkube_controller_sync_service_latency_seconds_bucket{job=\"ovnkube-node\"}[2m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ovnkube_controller_sync_service_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum by(pod) (rate(ovnkube_controller_sync_service_total{namespace=\"openshift-ovn-kubernetes\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "OCP ControlPlane Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } }
 ]
}